const OWNER_UID = "mHOKC2jtXcO7MvdQZNIuaSspLcD2";
const CLOUDINARY_CLOUD_NAME = "tyy4s335";
const CLOUDINARY_UPLOAD_PRESET = "sourav_portfolio";
const loginForm=document.getElementById('login-form'), authStatus=document.getElementById('auth-status'), publisher=document.getElementById('publisher'), logoutBtn=document.getElementById('logout'), postForm=document.getElementById('post-form'), postStatus=document.getElementById('post-status'), postList=document.getElementById('post-list');
const uploadPublishBtn=document.getElementById('upload-publish');
loginForm.addEventListener('submit',async e=>{e.preventDefault();authStatus.textContent='Signing in…';try{const cred=await portfolioAuth.signInWithEmailAndPassword(document.getElementById('email').value.trim(),document.getElementById('password').value);if(cred.user.uid!==OWNER_UID){await portfolioAuth.signOut();throw new Error('This account is not authorized as the site owner.');}authStatus.textContent='Signed in successfully.';}catch(err){authStatus.textContent=err.message||'Sign-in failed.';}});
logoutBtn.addEventListener('click',()=>portfolioAuth.signOut());
portfolioAuth.onAuthStateChanged(user=>{const owner=!!user&&user.uid===OWNER_UID;publisher.classList.toggle('hidden',!owner);logoutBtn.classList.toggle('hidden',!owner);loginForm.classList.toggle('hidden',owner);if(user&&!owner){authStatus.textContent='This account is not authorized.';portfolioAuth.signOut();}if(owner){authStatus.textContent='Signed in as owner.';loadPosts();}});
function getPostDetails(){return {title:document.getElementById('post-title').value.trim(),body:document.getElementById('post-body').value.trim(),category:document.getElementById('post-category').value};}
async function savePost(details){const user=portfolioAuth.currentUser;if(!user||user.uid!==OWNER_UID)throw new Error('Please sign in with the owner account.');await portfolioDb.collection('posts').add({...details,published:true,createdAt:firebase.firestore.FieldValue.serverTimestamp(),authorUid:user.uid});}
postForm.addEventListener('submit',async e=>{e.preventDefault();const d=getPostDetails();if(!d.title){postStatus.textContent='Please enter a title.';return;}postStatus.textContent='Publishing text post…';try{await savePost(d);postForm.reset();postStatus.textContent='Text post published.';loadPosts();}catch(err){postStatus.textContent='Could not publish: '+err.message;}});
uploadPublishBtn.addEventListener('click',async()=>{const user=portfolioAuth.currentUser;if(!user||user.uid!==OWNER_UID){postStatus.textContent='Please sign in with the owner account.';return;}const d=getPostDetails(),file=document.getElementById('post-file').files[0];if(!d.title){postStatus.textContent='Please enter a title.';return;}if(!file&&!d.body){postStatus.textContent='Add a description or choose a file.';return;}if(file&&file.size>50*1024*1024){postStatus.textContent='File is larger than 50 MB. Choose a smaller file.';return;}uploadPublishBtn.disabled=true;try{let asset={};if(file){postStatus.textContent='Uploading file to Cloudinary…';const form=new FormData();form.append('file',file);form.append('upload_preset',CLOUDINARY_UPLOAD_PRESET);form.append('folder','sourav-portfolio');const resourceType=file.type.startsWith('image/')?'image':(file.type.startsWith('video/')||file.type.startsWith('audio/'))?'video':'raw';const response=await fetch('https://api.cloudinary.com/v1_1/'+CLOUDINARY_CLOUD_NAME+'/'+resourceType+'/upload',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'Cloudinary upload failed. Check preset settings and allowed formats.');asset={fileUrl:result.secure_url,fileName:file.name,fileType:file.type||'application/octet-stream',resourceType:result.resource_type};}postStatus.textContent='Saving post…';await savePost({...d,...asset});postForm.reset();postStatus.textContent='Post published successfully.';loadPosts();}catch(err){postStatus.textContent='Could not publish: '+err.message;}finally{uploadPublishBtn.disabled=false;}});
async function loadPosts(){postList.textContent='Loading…';try{const snap=await portfolioDb.collection('posts').orderBy('createdAt','desc').limit(50).get();postList.innerHTML='';if(snap.empty){postList.textContent='No posts yet.';return;}snap.forEach(doc=>{const data=doc.data(),row=document.createElement('div');row.className='post-row';const h=document.createElement('h3');h.textContent=data.title||'(untitled)';const p=document.createElement('p');p.className='small';p.textContent=(data.category||'')+' · '+(data.fileName||'Text post')+' · '+(data.published?'Published':'Draft');const del=document.createElement('button');del.className='admin-btn secondary';del.textContent='Delete';del.addEventListener('click',async()=>{if(confirm('Delete this post? The Cloudinary file will remain stored.')){try{await portfolioDb.collection('posts').doc(doc.id).delete();loadPosts();}catch(e){postStatus.textContent=e.message;}}});row.append(h,p,del);postList.append(row);});}catch(err){postList.textContent='Unable to load posts: '+err.message;}}
